//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kastelo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kastelo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the password for this store?.
        /// </summary>
        internal static string Are_you_sure_password_change {
            get {
                return ResourceManager.GetString("Are_you_sure_password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password change.
        /// </summary>
        internal static string Confirm_password_change {
            get {
                return ResourceManager.GetString("Confirm_password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Files (*.bin)|*.bin.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is likely because of 4 reasons:
        ///1. You have entered the wrong password for this store.
        ///2. The store is not a valid store, try a different file.
        ///3. The store was encrypted using an invalid key.
        ///4. The store has been &apos;touched&apos; / edited.
        /// </summary>
        internal static string Form1_btnLoadFromFile_ExceptionMsg {
            get {
                return ResourceManager.GetString("Form1_btnLoadFromFile_ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load this data store.
        /// </summary>
        internal static string Form1_btnLoadFromFile_Unable_to_load_this_data_store {
            get {
                return ResourceManager.GetString("Form1_btnLoadFromFile_Unable_to_load_this_data_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for this store was incorrect..
        /// </summary>
        internal static string Incorrect_password_for_store {
            get {
                return ResourceManager.GetString("Incorrect_password_for_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load the same store as last time?.
        /// </summary>
        internal static string load_the_same_store {
            get {
                return ResourceManager.GetString("load_the_same_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string Password_changed {
            get {
                return ResourceManager.GetString("Password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for this store has been changed successfully.
        ///
        ///DON&apos;T FORGET IT!.
        /// </summary>
        internal static string Password_changed_successfully {
            get {
                return ResourceManager.GetString("Password_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload previous item?.
        /// </summary>
        internal static string Reload_previous_item {
            get {
                return ResourceManager.GetString("Reload_previous_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Store.
        /// </summary>
        internal static string Save_Store {
            get {
                return ResourceManager.GetString("Save_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the password you have entered is incorrect..
        /// </summary>
        internal static string Sorry_password_entered_incorrect {
            get {
                return ResourceManager.GetString("Sorry_password_entered_incorrect", resourceCulture);
            }
        }
    }
}
